learnfast/learnfast/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping_cart/', include('shopping_cart.urls', namespace="shopping_cart")),
    path('', include('sis.urls')),
    path('', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

learnfast/shopping_cart/urls.py
from django.conf.urls import url
from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    process_payment,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name="delete_item"),
    url(r'^checkout/$', checkout, name='checkout'),
    #url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name="process_payment"),
    url(r'^update-transaction/(?P<id>[-\w]+)/$', update_transaction_records, name="update_records"),
]

learnfast/sis/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'sis'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    #re_path(r'^home/$', views.home, name='home'),
    path('tutor_list', views.tutor_list, name='tutor_list'),
    path('course_list', views.course_list, name='course_list'),
    path('schedule_list', views.schedule_list, name='schedule_list'),
    path('register/', views.register, name='register'),

    # reset password urls
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('about_us', views.about_us, name='about_us'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('student_home', views.student_home, name='student_home'),

    path('tutor_dashboard', views.tutor_dashboard, name='tutor_dashboard'),
    path('tutor_home', views.tutor_home, name='tutor_home'),
    path('tutor_profile', views.tutor_profile, name='tutor_profile'),
    path('tutor_courses', views.tutor_courses, name='tutor_courses'),
    path('tutor_rosters', views.tutor_rosters, name='tutor_rosters'),
    path('tutor_wage', views.tutor_wage, name='tutor_wage'),

]

learnfast/sis/models.py
from django.db import models
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User

# Create your models here.
class Student(models.Model):
    stud_name = models.CharField(max_length=100)
    stud_address = models.CharField(max_length=200)
    stud_city = models.CharField(max_length=50)
    stud_zip = models.CharField(max_length=10)
    stud_email = models.CharField(max_length=50)
    stud_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.stud_name)

class Tutor(models.Model):
    tutor_id = models.IntegerField(primary_key=True, default=0)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tutor_name = models.CharField(max_length=50)
    # tutor_name = models.ForeignKey('Profile', related_name='contents', on_delete=models.CASCADE)
    tutor_zip = models.CharField(max_length=10)
    tutor_email = models.CharField(max_length=50)
    tutor_phone = models.CharField(max_length=50)
    tutor_sub_expertise = models.CharField(max_length=50)
    tutor_bank = models.CharField(max_length=100)
    tutor_rt_num = models.CharField(max_length=10)
    tutor_acct_num = models.CharField(max_length=100)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.tutor_name)

class Course(models.Model):
    course_id = models.IntegerField(primary_key=True, default=0)
    course_name = models.CharField(max_length=100)
    course_description = models.TextField(blank=True)
    course_subject = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.course_name)

class Room(models.Model):
    room_id = models.IntegerField(primary_key=True, default=0)
    room_number = models.CharField(max_length=100)
    room_capacity = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.room_number)


class Schedule(models.Model):
    schedule_id = models.IntegerField()
    #schedule_course_name = models.CharField(max_length=100)
    schedule_course_name = models.ForeignKey(Course, related_name='contents', on_delete=models.CASCADE)
    schedule_room_number = models.ForeignKey(Room, related_name='contents', on_delete=models.CASCADE)
    schedule_tutor_name = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='schedulelist', on_delete=models.CASCADE)
    # tutor_email = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='email', on_delete=models.CASCADE)
    schedule_date = models.DateField()
    schedule_time = models.TimeField()
    schedule_notes = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now_add=True)
#    max_seat = models.IntegerField()


    def created(self):
        self.created = timezone.now()
        self.save()

    def updated(self):
        self.updated = timezone.now()
        self.save()

    def __str__(self):
        return str(self.schedule_course_name)

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    schedules = models.ManyToManyField(Schedule, blank=True)

    def __str__(self):
        return self.user.username


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

learnfast/sis/forms.py
from django import forms
from .models import Course, Tutor
from django.contrib.auth.models import User, Group

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('course_name', 'course_description', 'course_subject')

# class TutorForm(forms.ModelForm):
#     class Meta:
#         model = Tutor
#         fields = ('tutor_name', 'tutor_address', 'tutor_city', 'tutor_zip', 'tutor_email', 'tutor_phone', 'tutor_sub_expertise')

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

learnfast/sis/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from shopping_cart.models import Order
from .forms import UserRegistrationForm
from django.contrib.auth.models import Group


@login_required
def student_home(request):
    return render(request, 'sis/student_home.html', {'sis': student_home})

@login_required
def tutor_list(request):
    tutor = Tutor.objects.filter(created_date__lte=timezone.now())
    return render(request, 'sis/tutor_list.html', {'tutors': tutor})

@login_required
def course_list(request):
    course = Course.objects.filter(created_date__lte=timezone.now())
    return render(request, 'sis/course_list.html', {'courses': course})

@login_required
def schedule_list(request):
    object_list = Schedule.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_schedules = []
    if filtered_orders.exists():
        user_order = filtered_orders[0]
        user_order_items = user_order.items.all()
        current_order_schedules = [schedule.schedule for schedule in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_schedules': current_order_schedules
    }

    return render(request, "sis/schedule_list.html", context)

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            group = Group.objects.get(name='student')
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            new_user.groups.add(Group.objects.get(name='student'))
            return render(request,
                          'sis/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'sis/register.html',
                  {'user_form': user_form})

def my_profile(request):
    my_user_profile = Profile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
    context = {
        'my_orders':my_orders
    }
    return render(request, "profile.html", context)


now = timezone.now()
def about_us(request):
    return render(request, 'sis/about_us.html', {'sis': about_us})

now = timezone.now()
def contact_us(request):
    return render(request, 'sis/contact_us.html', {'sis': contact_us})

@login_required
def tutor_dashboard(request):
    schedule = Schedule.objects.filter(schedule_tutor_name=request.user)
    return render(request, 'sis/tutor_dashboard.html', {'schedules': schedule})


@login_required
def tutor_home(request):
    return render(request, 'sis/tutor_home.html')


@login_required
def tutor_profile(request):
    tutor = Profile.objects.filter(user=request.user)
    return render(request, 'sis/tutor_profile.html', {'tutors': tutor})


@login_required
def tutor_courses(request):
    course = Course.objects.filter(created_date__lte=timezone.now())
    return render(request, 'sis/tutor_courses.html', {'courses': course})


@login_required
def tutor_rosters(request):
    student = Student.objects.filter(created_date__lte=timezone.now())
    return render(request, 'sis/tutor_rosters.html', {'students': student})


@login_required
def tutor_wage(request):
    student = Student.objects.filter(created_date__lte=timezone.now())
    course = Course.objects.filter(created_date__lte=timezone.now())
    schedule = Schedule.objects.filter(created_date__lte=timezone.now())
    sum_stud_name = Student.objects.filter(created_date__lte=timezone.now()).aggregate(Sum('stud_name'))
    return render(request, 'sis/tutor_wage.html', {'students': student, 'tutors': tutor, 'courses': course,
                                                 'schedules': schedule, 'sum_stud_name': sum_stud_name})


now = timezone.now()
def landing_page(request):
    return render(request, 'sis/landing_page.html', {'sis': landing_page})

learnfast/sis/templates/sis/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learn Fast Tutoring</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body id="app-layout">
    <nav class="navbar-expand-md bg-success navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>


                <a class="navbar-brand" href="/">Learn Fast</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'sis:about_us' %}">About Us</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:student_home' %}">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:schedule_list' %}">Enroll</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:contact_us' %}">Contact Us</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{% url 'logout' %}">
                                        <i class="fa fa-btn fa-sign-out"></i>Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                    <div class="links">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static 'image/about_us.png' %}" alt="about us"/></a>
                                    <div class="caption">
                                        <h3>About Us</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'sis:schedule_list' %}"><img src="{% static 'image/enroll.jpg' %}" alt="enroll"/></a>
                                    <div class="caption">
                                        <h3>Enroll</h3>
                                        {% if user.is_authenticated %}
                                            <p><a class="btn btn-default" href="{% url 'sis:schedule_list'%}" role="button">Click to View Classes &raquo;</a></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static 'image/contact_us.jpg' %}" alt="contact us"/></a>
                                    <div class="caption">
                                        <h3>Contact Us</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

learnfast/sis/templates/sis/course_list.html
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Learn Fast</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {background-color: beige;}
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Learn Fast For a Better Future!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Course Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Course</th>
                    <th>Description</th>
                    <th>Subject Category</th>
                    <th colspan="3">Summary</th>
                </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course_name }}</td>
                    <td>{{ course.course_description }}</td>
                    <td>{{ course_subject }}</td>
                    <td><a href="" class="btn btn-primary">Summary</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </body>
    </html>
{% endblock %}

learnfast/sis/templates/sis/student_home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'sis/base.html' %}
{% load staticfiles %}
{% block content %}
    <body>
        {% if user.is_authenticated %}
            <div class="container">
                <h2 class="top-menu">Hello {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}
        <div class="content container">
            <div class="row">
                <div class="col-md-12">
                    <div class="links">
                        <!-- Example row of columns -->
                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/dashboard.png" %}" alt="dashboard"/></a>
                                    <div class="caption">
                                        <h3>Dashboard</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'sis:schedule_list' %}"><img src="{% static "image/enroll.jpg" %}" alt="enroll"/></a>
                                    <div class="caption">
                                        <h3>Enroll</h3>
                                        {% if user.is_authenticated %}
                                            <p><a class="btn btn-default" href="{% url 'sis:schedule_list'%}" role="button">Click to View Classes &raquo;</a></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'shopping_cart:order_summary' %}"><img src="{% static "image/checkout.png" %}" alt="checkout"/></a>
                                    <div class="caption">
                                        <h3>Checkout</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </body>
{% endblock %}


</html>

learnfast/sis/templates/sis/tutor_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learn Fast Tutoring</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/portfolio.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body id="app-layout">
    <nav class="navbar-expand-md bg-success navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
               <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                   <!-- Branding Image -->
                <a class="navbar-brand" href="{% url 'sis:tutor_home' %}">Learn Fast</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'sis:tutor_dashboard' %}">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:tutor_profile' %}">Profile</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:tutor_courses' %}">All Courses</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:tutor_rosters' %}">Rosters</a>
                    </li>
                    <li>
                        <a href="{% url 'sis:tutor_wage' %}">My Wages</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{% url 'logout' %}">
                                        <i class="fa fa-btn fa-sign-out"></i>Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                    <div class="links">
                         <!-- Example row of columns -->
                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/about_us.png" %}" alt="about us"/></a>
                                    <div class="caption">
                                        <h3>About Us</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href="{% url 'sis:schedule_list' %}"><img src="{% static "image/enroll.jpg" %}" alt="enroll"/></a>
                                    <div class="caption">
                                        <h3>Enroll</h3>
                                        {% if user.is_authenticated %}
                                            <p><a class="btn btn-default" href="{% url 'sis:schedule_list'%}" role="button">Click to View Classes &raquo;</a></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="thumbnail">
                                    <a href=""><img src="{% static "image/contact_us.jpg" %}" alt="contact us"/></a>
                                    <div class="caption">
                                        <h3>Contact Us</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

learnfast/sis/templates/sis/tutor_home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'sis/tutor_base.html' %}
{% load staticfiles %}
{% block content %}
    <body>
        {% if user.is_authenticated %}
            <div class="container">
                <h2 class="top-menu">Hello {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}
        <div class="content container">
            <div class="row">
                <div class="col-md-12">
                    <div class="links">
                        <!-- Example row of columns -->
                        <div class="row">
                        	<div class="col-md-3">
								<div class="thumbnail" style="border: none">
							    	<a href="{% url 'sis:tutor_dashboard'%}"><img src="{% static "image/dashboard.png" %}" style="height: 225px; width: 225px;" alt="dashboard"/></a>
							        	<div class="caption">
							            	<a href="{% url 'sis:tutor_dashboard'%}"> <h3>Dashboard</h3></a>
							            </div>
							     </div>
                            </div>
                            <div class="col-md-3">
                                <div class="thumbnail" style="border: none">
                                    <a href="{% url 'sis:tutor_courses'%}"><img src="{% static "image/AllClasses.jpg" %}" style="height: 225px; width: 225px;" alt="AllClasses"/></a>
                                    <div class="caption">
                                        {% if user.is_authenticated %}
                                            <a href="{% url 'sis:tutor_courses'%}"> <h3>All Classes</h3></a>
										   <!--<p><a class="btn btn-default" href="{% url 'sis:tutor_courses'%}" role="button">Click to View Classes &raquo;</a></p>-->
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="thumbnail" style="border: none">
                                    <a href="{% url 'sis:tutor_rosters' %}"><img src="{% static "image/students.jpg" %}" style="height: 225px; width: 225px;" alt="AllStudents"/></a>
                                    <div class="caption">
                                        {% if user.is_authenticated %}
                                            <a href="{% url 'sis:tutor_rosters'%}"> <h3>All Students</h3></a>
                                            <!--<p><a class="btn btn-default" href="{% url 'sis:tutor_rosters'%}" role="button">Click to View Students &raquo;</a></p>-->
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="thumbnail" style="border: none">
                                    <a href="{% url 'sis:tutor_wage'%}"><img src="{% static "image/Payment.jpg" %}" style="height: 225px; width: 225px;" alt="Tutor Wage"/></a>
                                    <div class="caption">
                                        {% if user.is_authenticated %}
                                            <a href="{% url 'sis:tutor_wage'%}"> <h3>My Wages</h3></a>
											<!--<p><a class="btn btn-default" href="{% url 'sis:tutor_wage'%}" role="button">Click to View Wages &raquo;</a></p>-->
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock %}


</html>